# Generated by CoffeeScript 1.4.0
(->
  $("#switch1").mouseover ->
    $("#menu1").show()

  $("#switch1").mouseout ->
    $("#menu1").hide()

  $("#switch2").mouseover ->
    $("#menu2").show()

  $("#switch2").mouseout ->
    $("#menu2").hide()

  $("#switch3").mouseover ->
    $("#menu3").show()

  $("#switch3").mouseout ->
    $("#menu3").hide()

  return
).call this
$(document).ready ->
  $("#remove_photo, #remove_photo1").click (e) ->
    result = window.confirm("Are you sure you want to remove this picture ?")
    unless result
      e.preventDefault()
      e.event.stopPropagation()
      return false
    e.event.stopPropagation()
    return

  
  #initialise this to the current active image
  id = $(".carousel2").find(".active").attr("photoid")
  $("#remove_photo").attr "href", "/photo/" + id + "/remove"
  $(".album_item").click ->
    id = $(this).attr("data-photoid")
    $("#remove_photo").attr "href", "/photo/" + id + "/remove"
    return

  $(".carousel1").carousel interval: false
  $(".carousel2").carousel(interval: false).on "slid.bs.carousel", (e) ->
    xx = $(this)
    id = xx.find(".active").attr("photoid")
    $("#remove_photo").attr "href", "/photo/" + id + "/remove"
    return

  return
